#!/bin/bash
# Installation:
#   Copy this script as pre-commit to .git/hooks folder

OPTIONS="--options=astyle-options.txt"


# Check if .gitignore file exists
if [ ! -f astyle-options.txt ]; then
    echo "[!] astyle-options.txt file not found. Please make sure the astyle-options.txt file is present." >&2
    exit 1
fi

RETURN=0
ASTYLE=$(command -v astyle)
if [ $? -ne 0 ]; then
    echo "[!] AStyle is not installed. Unable to check source file format policy." >&2
    exit 1
fi

# Check if .gitignore file exists
if [ ! -f .gitignore ]; then
    echo "[!] .gitignore file not found. Please make sure the .gitignore file is present." >&2
    exit 1
fi

# Check if README.md file exists
if [ ! -f README.md ]; then
    echo "[!] README.md file not found. Please make sure the README.md file is present." >&2
    exit 1
fi

# Check if DoxyfileLibLinux file exists
if [ ! -f DoxyfileLibLinux ]; then
    echo "[!] DoxyfileLibLinux file not found. Please make sure the DoxyfileLibLinux file is present." >&2
    exit 1
fi

# Check if DoxyfileLibWin file exists
if [ ! -f DoxyfileLibWin ]; then
    echo "[!] DoxyfileLibWin file not found. Please make sure the DoxyfileLibWin file is present." >&2
    exit 1
fi

# Check if DoxyfileTestLinux file exists
if [ ! -f DoxyfileTestLinux ]; then
    echo "[!] DoxyfileTestLinux file not found. Please make sure the DoxyfileTestLinux file is present." >&2
    exit 1
fi

# Check if DoxyfileTestWin file exists
if [ ! -f DoxyfileTestWin ]; then
    echo "[!] DoxyfileTestWin file not found. Please make sure the DoxyfileTestWin file is present." >&2
    exit 1
fi

FILES=$(git diff --cached --name-only --diff-filter=ACMRTUXB | grep -E "\.(cs|java|c|cpp|h)$")
for FILE in $FILES; do
    FORMATTED=$( "$ASTYLE" $OPTIONS < "$FILE" 2>&1 )
    if [ $? -ne 0 ]; then
        echo "[!] Error formatting $FILE:" >&2
        echo "$FORMATTED" >&2
        RETURN=1
    elif [ -n "$FORMATTED" ]; then
        echo "Formatted $FILE"
        echo "$FORMATTED"
        echo ""
        echo "$FORMATTED" > "$FILE"
        git add "$FILE"
    fi
done

if [ $RETURN -eq 1 ]; then
    echo "" >&2
    echo "Make sure you have run AStyle with the following options:" >&2
    echo $OPTIONS >&2
fi

exit $RETURN
