#!/usr/bin/env python3
"""Zip every generated HTML report folder for the site's "Download (zip)" buttons.

Run after the reports are generated (Doxygen, ReportGenerator, OpenCppCoverage /
lcov genhtml / gcovr, junit2html) and before ``mkdocs build``, so the zip files
land inside ``docs/`` and mkdocs copies them into ``site/`` automatically, next
to the report folders themselves.

This is the single source of truth for "which report pages does the site have"
(REPORTS below): ``docs/reports/<id>.md`` (one hand-written page per entry, see
that folder) links to ``../../<zip_source>`` for "Open in a new tab" style
links and to ``../../<id>.zip`` for the "Download (zip)" button - both are two
levels up from ``docs/reports/<id>/`` in the built site, since every entry
lives at the same nesting depth. If you add a new report here, also add the
matching ``docs/reports/<id>.md`` page (copy an existing one) and a line in
``mkdocs.yml``'s "Reports" nav section.

Usage:
    python3 tools/zip_reports.py [--docs-dir docs]

Missing report folders (e.g. the Linux reports when only
7-build-app-windows.bat has been run) are skipped with a note, not an error -
same "skip gracefully" policy as the rest of this template's optional tools.
"""
from __future__ import annotations

import argparse
import os
import sys
import zipfile
from pathlib import Path

# id, title, platform, description, zip_source (relative to docs/, folder or
# file to archive), iframe_src (relative to docs/, the report's own index.html)
REPORTS = [
    # --- Windows -----------------------------------------------------------
    ("doxygen-lib-win", "Library API Documentation (Doxygen)", "Windows",
     "API documentation generated by Doxygen from the calculator and utility "
     "library headers/sources (Doxygen comments). This is the ecosystem-native "
     "C++ \"site\" for the library.",
     "doxygenlibwin/html", "doxygenlibwin/html/index.html"),
    ("doxygen-test-win", "Unit Test Source Documentation (Doxygen)", "Windows",
     "The same, but for the googletest test sources under src/tests, so you "
     "can browse what each test covers.",
     "doxygentestwin/html", "doxygentestwin/html/index.html"),
    ("test-results-win", "Unit Test Results (native)", "Windows",
     "The native unit-test results report: pass/fail per test case, straight "
     "from CTest's own JUnit XML output (CTest --output-junit, converted by "
     "junit2html). No coverage information, just pass/fail and timing.",
     "testresultswin", "testresultswin/index.html"),
    ("coverage-reportgenerator-win", "Code Coverage (ReportGenerator)", "Windows",
     "Code coverage: which lines/branches/methods of calculator, utility and "
     "calculatorapp were executed by the googletest suite, as an HTML report "
     "from ReportGenerator (with history charts across builds).",
     "coveragereportlibwin", "coveragereportlibwin/index.html"),
    ("coverage-native-win", "Code Coverage (native: OpenCppCoverage)", "Windows",
     "The same code-coverage data, as OpenCppCoverage's own native HTML "
     "export (--export_type=html). Compare its numbers with the "
     "ReportGenerator report - they should match.",
     "coveragenativelibwin", "coveragenativelibwin/index.html"),
    ("doccoverage-lib-reportgenerator-win", "Library Documentation Coverage (ReportGenerator)", "Windows",
     "Documentation coverage for the library: what fraction of public "
     "functions/classes have a Doxygen comment (coverxygen output rendered by "
     "ReportGenerator). Not the same thing as test/code coverage.",
     "coverxygenlibwin", "coverxygenlibwin/index.html"),
    ("doccoverage-lib-native-win", "Library Documentation Coverage (native: lcov genhtml)", "Windows",
     "The same documentation-coverage data for the library, as a native "
     "lcov genhtml HTML report.",
     "coverxygennativelibwin", "coverxygennativelibwin/index.html"),
    ("doccoverage-test-reportgenerator-win", "Test Documentation Coverage (ReportGenerator)", "Windows",
     "Documentation coverage for the googletest test sources themselves "
     "(coverxygen output rendered by ReportGenerator).",
     "coverxygentestwin", "coverxygentestwin/index.html"),
    ("doccoverage-test-native-win", "Test Documentation Coverage (native: lcov genhtml)", "Windows",
     "The same documentation-coverage data for the tests, as a native lcov "
     "genhtml HTML report.",
     "coverxygennativetestwin", "coverxygennativetestwin/index.html"),
    # --- Linux ---------------------------------------------------------------
    ("doxygen-lib-linux", "Library API Documentation (Doxygen)", "Linux",
     "API documentation generated by Doxygen from the calculator and utility "
     "library headers/sources (Doxygen comments). This is the ecosystem-native "
     "C++ \"site\" for the library.",
     "doxygenliblinux/html", "doxygenliblinux/html/index.html"),
    ("doxygen-test-linux", "Unit Test Source Documentation (Doxygen)", "Linux",
     "The same, but for the googletest test sources under src/tests, so you "
     "can browse what each test covers.",
     "doxygentestlinux/html", "doxygentestlinux/html/index.html"),
    ("test-results-linux", "Unit Test Results (native)", "Linux",
     "The native unit-test results report: pass/fail per test case, straight "
     "from CTest's own JUnit XML output (CTest --output-junit, converted by "
     "junit2html). No coverage information, just pass/fail and timing.",
     "testresultslinux", "testresultslinux/index.html"),
    ("coverage-reportgenerator-linux", "Code Coverage (ReportGenerator)", "Linux",
     "Code coverage: which lines/branches/methods of calculator, utility and "
     "calculatorapp were executed by the googletest suite, as an HTML report "
     "from ReportGenerator (with history charts across builds).",
     "coveragereportliblinux", "coveragereportliblinux/index.html"),
    ("coverage-native-linux", "Code Coverage (native: lcov genhtml + gcovr)", "Linux",
     "The same code-coverage data, as lcov's own genhtml HTML report, with "
     "gcovr's independent HTML report alongside it (coveragenativeliblinux/gcovr) "
     "when gcovr is installed. Compare all three - they should agree.",
     "coveragenativeliblinux", "coveragenativeliblinux/index.html"),
    ("doccoverage-lib-reportgenerator-linux", "Library Documentation Coverage (ReportGenerator)", "Linux",
     "Documentation coverage for the library: what fraction of public "
     "functions/classes have a Doxygen comment (coverxygen output rendered by "
     "ReportGenerator). Not the same thing as test/code coverage.",
     "coverxygenliblinux", "coverxygenliblinux/index.html"),
    ("doccoverage-lib-native-linux", "Library Documentation Coverage (native: lcov genhtml)", "Linux",
     "The same documentation-coverage data for the library, as a native "
     "lcov genhtml HTML report.",
     "coverxygennativeliblinux", "coverxygennativeliblinux/index.html"),
    ("doccoverage-test-reportgenerator-linux", "Test Documentation Coverage (ReportGenerator)", "Linux",
     "Documentation coverage for the googletest test sources themselves "
     "(coverxygen output rendered by ReportGenerator).",
     "coverxygentestlinux", "coverxygentestlinux/index.html"),
    ("doccoverage-test-native-linux", "Test Documentation Coverage (native: lcov genhtml)", "Linux",
     "The same documentation-coverage data for the tests, as a native lcov "
     "genhtml HTML report.",
     "coverxygennativetestlinux", "coverxygennativetestlinux/index.html"),
]


def zip_reports(docs_dir: Path) -> int:
    made, skipped = 0, 0
    for report_id, title, _platform, _desc, zip_source, iframe_src in REPORTS:
        src = docs_dir / zip_source
        if not src.is_dir():
            print(f"[zip_reports] skip {report_id}: {src} does not exist yet")
            skipped += 1
            continue
        entry_point = docs_dir / iframe_src
        if not entry_point.is_file():
            # The folder exists but the report's own entry-point page (e.g.
            # index.html) does not - a tool failed/timed out partway through
            # for this run (e.g. the documented WSL2 lcov/gcovr hang, or an
            # old Windows lcov genhtml drive-letter-path bug - see
            # docs/guide/troubleshooting.en.md) and left only partial output
            # (CSS/images, an empty dir, ...). Skip it rather than shipping a
            # misleading near-empty/0 KiB zip and a report page that 404s.
            print(f"[zip_reports] skip {report_id}: {entry_point} was not produced "
                  f"(the report tool likely failed/timed out this run - {src} has partial output)")
            skipped += 1
            continue
        dest = docs_dir / f"{report_id}.zip"
        with zipfile.ZipFile(dest, "w", zipfile.ZIP_DEFLATED) as zf:
            for root, _dirs, files in os.walk(src):
                for name in files:
                    file_path = Path(root) / name
                    zf.write(file_path, file_path.relative_to(src))
        size_kb = dest.stat().st_size / 1024
        print(f"[zip_reports] wrote {dest} ({size_kb:.0f} KiB) for '{title}'")
        made += 1
    print(f"[zip_reports] done: {made} zip(s) written, {skipped} report(s) not yet built")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-dir", default="docs", help="path to the mkdocs docs_dir (default: docs)")
    args = parser.parse_args()
    return zip_reports(Path(args.docs_dir))


if __name__ == "__main__":
    sys.exit(main())
